version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data/instance:/app/instance
    environment:
      - SECRET_KEY=${SECRET_KEY:-changeme_in_production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=${FLASK_ENV:-development}
      # Uncomment for PostgreSQL:
      # - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-diary_db}
    depends_on:
      # Uncomment for PostgreSQL:
      # - db
    restart: unless-stopped

  # Uncomment for PostgreSQL:
  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=${DB_USER:-postgres}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
  #     - POSTGRES_DB=${DB_NAME:-diary_db}
  #   restart: unless-stopped

# Uncomment for PostgreSQL:
# volumes:
#   postgres_data: